version: "3"
services:
  npm:
    build: .
    container_name: kitchen-node
    volumes:
      - ./app:/app
#    working_dir: /app
#    command: /bin/sh -c "ls"
#  nginx:
#    container_name: kitchen-nginx
#    image: nginx
#    ports:
#      - 80:80
#    volumes:
#      - ./app/dist:/usr/share/nginx/html
#    depends_on:
#      - npm


