version: "3"
services:
  nginx:
    container_name: kitchen-nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./app/dist:/usr/share/nginx/html
  server:
    build:
      context: ./service
      dockerfile: Dockerfile
    container_name: kitchen-server
    ports:
      - 8080:8080

