version: "3"
services:
  mysql:
    container_name: kitchen-mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'k_kitchen_123456'
      MYSQL_DATABASE: 'kitchen'
    volumes:
      - ./_store/mysql-data:/var/lib/mysql
  nginx:
    container_name: kitchen-nginx
    restart: always
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./app/dist:/usr/share/nginx/html
  server:
    build:
      context: ./service
      dockerfile: Dockerfile
    container_name: kitchen-server
    restart: always
    volumes:
      - ./_store/more_static:/root/more_static
    depends_on:
      - mysql
      - nginx
    ports:
      - 8080:8080
    # 需要等待mysql ready状态
    command: /bin/sh -c "sleep 2 && ./kitchen-server"
