version: "3"
services:
  mysql:
    container_name: kitchen-mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'k_kitchen_123456'
      MYSQL_DATABASE: 'kitchen'
    volumes:
      - ./_store/mysql-data:/var/lib/mysql
  nginx:
    container_name: kitchen-nginx
    restart: always
    image: nginx
    ports:
      - "80:80"
    environment:
      # 域名或者ip
      - NGINX_HOST=wangqiqi.buzz
      # nginx监听请求端口
      - NGINX_PORT=80
      # api转发端口
      - SERVICE_API_PORT=8080
      # api路由
      - SERVICE_API_ROUTE=/api
      # 静态资源
      - NGINX_STATIC=/more_static
    volumes:
      # 静态文件目录
      - ./_store/more_static:/usr/share/nginx/more_static
      # 前端访问目录
      - ./app/dist:/usr/share/nginx/html
      # 用来配置nginx.conf的模版
      - ./conf:/etc/nginx/templates
  server:
    build:
      context: ./service
      dockerfile: Dockerfile
    container_name: kitchen-server
    restart: always
    volumes:
      - ./_store/more_static:/root/more_static
    environment:
      - mail_from=834971685@qq.com
      - mail_to=834971685@qq.com
      - mail_token=
    depends_on:
      - mysql
      - nginx
    ports:
      - "8080:8080"
    # 需要等待mysql ready状态
    command: /bin/sh -c "sleep 2 && ./kitchen-server"
