version: "3"
services:
  npm:
    container_name: node
    image: node
    volumes:
      - ./app:/app
    working_dir: /app
    command: /bin/sh -c "ls -al /app  && \ rm -rf package.json &&  npm install && npm run build"

